# Generated by Django 6.0.2 on 2026-03-01 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_uploadedpdf_user'),
        ('courses', '0007_remove_bookmark_legacy_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFPageChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('text_content', models.TextField()),
                ('image_paths', models.JSONField(default=list)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.uploadedpdf')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
            ],
            options={
                'ordering': ['pdf', 'page_number'],
            },
        ),
    ]
