# Generated by Django 6.0.2 on 2026-03-01 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_refactor_pdf_models'),
        ('courses', '0009_alter_semester_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pdfpagechunk',
            new_name='chatbot_pdf_text_co_e71b9d_idx',
            old_name='text_content_idx',
        ),
        migrations.AlterField(
            model_name='referencepdf',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        # backfill any existing ReferencePDF rows that were created before the
        # subject field was required.  We assign them to the first available
        # subject (creating a placeholder if none exists) so that the upcoming
        # NOT NULL constraint can be satisfied during the table recreation.
        migrations.RunPython(
            code=lambda apps, schema_editor: _populate_default_subject(apps),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='referencepdf',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_pdfs', to='courses.subject'),
        ),
        migrations.AlterField(
            model_name='referencepdf',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='referencepdf',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_pdfs', to=settings.AUTH_USER_MODEL),
        ),
    ]


def _populate_default_subject(apps):
    ReferencePDF = apps.get_model('chatbot', 'ReferencePDF')
    Subject = apps.get_model('courses', 'Subject')
    default = Subject.objects.first()
    if default is None:
        # create a minimal semester and subject to satisfy the FK
        Semester = apps.get_model('courses', 'Semester')
        semester, _ = Semester.objects.get_or_create(
            number=0,
            regulation='Unknown',
            defaults={'description': 'Auto-generated fallback semester', 'is_active': False},
        )
        default = Subject.objects.create(
            name='Unknown',
            description='Auto-generated fallback subject',
            semester=semester,
            subject_code='UNKNOWN',
            is_active=False,
        )
    ReferencePDF.objects.filter(subject__isnull=True).update(subject=default)
