# Generated by Django 6.0.2 on 2026-03-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_rename_text_content_idx_chatbot_pdf_text_co_e71b9d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencepdf',
            name='is_syllabus_reference',
            field=models.BooleanField(default=False),
        ),
    ]
