# Generated by Django 6.0.2 on 2026-03-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_alter_referencepdf_is_syllabus_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfpagechunk',
            options={'ordering': ['reference_pdf', 'page_number', 'chunk_index']},
        ),
        migrations.AddField(
            model_name='pdfpagechunk',
            name='chunk_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='pdfpagechunk',
            unique_together={('reference_pdf', 'page_number', 'chunk_index')},
        ),
        migrations.AddIndex(
            model_name='pdfpagechunk',
            index=models.Index(fields=['reference_pdf'], name='chatbot_pdf_referen_297923_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfpagechunk',
            index=models.Index(fields=['page_number'], name='chatbot_pdf_page_nu_9ae079_idx'),
        ),
    ]
