# Generated by Django 6.0.2 on 2026-03-05 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_alter_pdfpagechunk_options_pdfpagechunk_chunk_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('image_path', models.CharField(max_length=500)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('reference_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_images', to='chatbot.referencepdf')),
            ],
            options={
                'ordering': ['reference_pdf', 'page_number', 'id'],
                'indexes': [models.Index(fields=['reference_pdf', 'page_number'], name='chatbot_pdf_referen_66fbf1_idx')],
                'unique_together': {('reference_pdf', 'page_number', 'image_path')},
            },
        ),
    ]
