# Generated by Django 6.0.2 on 2026-03-13 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_pdfimage'),
        ('courses', '0011_alter_history_options_alter_lesson_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('normalized_question', models.CharField(blank=True, max_length=500)),
                ('strict_mode', models.BooleanField(default=True)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('result_reference_ids', models.JSONField(blank=True, default=list)),
                ('related_concepts', models.JSONField(blank=True, default=list)),
                ('response_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='referencepdf',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='pdfimage',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='referencepdf',
            name='chunk_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referencepdf',
            name='diagram_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referencepdf',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='referencepdf',
            name='is_rejected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='referencepdf',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referencepdf',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referencepdf',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='pdfpagechunk',
            name='reference_pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chatbot.referencepdf'),
        ),
        migrations.AlterField(
            model_name='referencepdf',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='referencepdf',
            name='is_syllabus_reference',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='pdfimage',
            index=models.Index(fields=['page_number'], name='chatbot_pdf_page_nu_ddfad1_idx'),
        ),
        migrations.AddIndex(
            model_name='referencepdf',
            index=models.Index(fields=['subject', 'is_active', 'is_approved', 'is_syllabus_reference'], name='chatbot_pdf_access_idx'),
        ),
        migrations.AddIndex(
            model_name='referencepdf',
            index=models.Index(fields=['uploaded_by', 'processing_status'], name='chatbot_pdf_owner_proc_idx'),
        ),
        migrations.AddField(
            model_name='chatquery',
            name='reference_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_queries', to='chatbot.referencepdf'),
        ),
        migrations.AddField(
            model_name='chatquery',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_queries', to='courses.subject'),
        ),
        migrations.AddField(
            model_name='chatquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatquery',
            index=models.Index(fields=['user', 'created_at'], name='chatbot_cha_user_id_6903e8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatquery',
            index=models.Index(fields=['created_at', 'result_count'], name='chatbot_cha_created_406086_idx'),
        ),
    ]
