# Generated by Django 6.0.2 on 2026-03-13 07:26

import django.db.models.deletion
from django.db import migrations, models


def migrate_completed_status_to_ready(apps, schema_editor):
    ReferencePDF = apps.get_model("chatbot", "ReferencePDF")
    ReferencePDF.objects.filter(processing_status="COMPLETED").update(processing_status="READY")


def migrate_ready_status_to_completed(apps, schema_editor):
    ReferencePDF = apps.get_model("chatbot", "ReferencePDF")
    ReferencePDF.objects.filter(processing_status="READY").update(processing_status="COMPLETED")


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_chatquery_alter_referencepdf_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_completed_status_to_ready,
            migrate_ready_status_to_completed,
        ),
        migrations.AlterField(
            model_name='referencepdf',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.JSONField(default=list)),
                ('model_name', models.CharField(default='all-MiniLM-L6-v2', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='chatbot.pdfpagechunk')),
            ],
            options={
                'ordering': ['chunk_id'],
                'indexes': [models.Index(fields=['model_name'], name='chatbot_chu_model_n_dbf6dc_idx')],
            },
        ),
    ]
