# Generated by Django 6.0.2 on 2026-03-13 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_alter_referencepdf_processing_status_chunkembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('related_concepts', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='chatbot_con_name_5c9325_idx'), models.Index(fields=['slug'], name='chatbot_con_slug_2225e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChunkConceptLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=0.0)),
                ('extraction_method', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_links', to='chatbot.pdfpagechunk')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_links', to='chatbot.conceptnode')),
            ],
            options={
                'ordering': ['chunk_id', '-relevance_score', 'concept__name'],
                'indexes': [models.Index(fields=['chunk', 'concept'], name='chatbot_chu_chunk_i_4e14db_idx'), models.Index(fields=['concept', 'relevance_score'], name='chatbot_chu_concept_24d90b_idx')],
                'unique_together': {('chunk', 'concept')},
            },
        ),
        migrations.CreateModel(
            name='ConceptRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(default='relates_to', max_length=50)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='chatbot.conceptnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='chatbot.conceptnode')),
            ],
            options={
                'ordering': ['-weight', 'source__name', 'target__name'],
                'indexes': [models.Index(fields=['source', 'relation_type'], name='chatbot_con_source__e92211_idx'), models.Index(fields=['target', 'relation_type'], name='chatbot_con_target__75035c_idx')],
                'unique_together': {('source', 'target', 'relation_type')},
            },
        ),
    ]
