# Generated by Django 6.0.2 on 2026-03-13 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_conceptnode_chunkconceptlink_conceptrelation'),
        ('courses', '0012_alter_subject_subject_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='referencepdf',
            constraint=models.UniqueConstraint(fields=('title', 'subject'), name='unique_reference_pdf_title_per_subject'),
        ),
    ]
