# Generated by Django 6.0.2 on 2026-03-13 17:46

from django.conf import settings
from django.db import migrations, models


def populate_reference_pdf_status(apps, schema_editor):
    ReferencePDF = apps.get_model('chatbot', 'ReferencePDF')
    for pdf in ReferencePDF.objects.all().iterator():
        if getattr(pdf, 'is_rejected', False):
            pdf.status = 'rejected'
        elif getattr(pdf, 'is_approved', False):
            pdf.status = 'approved'
        elif getattr(pdf, 'processing_status', '') in {'PENDING', 'PROCESSING'}:
            pdf.status = 'processing'
        else:
            pdf.status = 'hold'
        pdf.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_referencepdf_unique_reference_pdf_title_per_subject'),
        ('courses', '0012_alter_subject_subject_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='referencepdf',
            name='chatbot_pdf_access_idx',
        ),
        migrations.AddField(
            model_name='referencepdf',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('hold', 'On Hold'), ('rejected', 'Rejected'), ('processing', 'Processing')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AddIndex(
            model_name='referencepdf',
            index=models.Index(fields=['subject', 'is_active', 'status', 'is_syllabus_reference'], name='chatbot_pdf_access_idx'),
        ),
        migrations.AddIndex(
            model_name='referencepdf',
            index=models.Index(fields=['uploaded_by', 'status'], name='chatbot_pdf_owner_status_idx'),
        ),
        migrations.RunPython(populate_reference_pdf_status, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='referencepdf',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='referencepdf',
            name='is_rejected',
        ),
    ]
