# Generated by Django 5.2.6 on 2026-03-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0016_remove_referencepdf_chatbot_pdf_access_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptAnswerCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("concept", models.CharField(max_length=150, unique=True)),
                ("best_answer", models.TextField()),
                ("references", models.JSONField(blank=True, default=list)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("quality_score", models.PositiveSmallIntegerField(default=0)),
                ("generation_mode", models.CharField(blank=True, max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "concept_answer_cache",
                "ordering": ["-quality_score", "-confidence_score", "concept"],
            },
        ),
        migrations.CreateModel(
            name="ConceptRelationship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("concept", models.CharField(db_index=True, max_length=150)),
                ("related_concept", models.CharField(db_index=True, max_length=150)),
                ("relation_type", models.CharField(default="relates_to", max_length=50)),
                ("weight", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "concept_relationships",
                "ordering": ["-weight", "concept", "related_concept"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=500)),
                ("subject_code", models.CharField(db_index=True, max_length=50)),
                ("concept", models.CharField(db_index=True, max_length=150)),
                ("is_processed", models.BooleanField(db_index=True, default=False)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("last_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_chunk",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="generated_questions", to="chatbot.pdfpagechunk"),
                ),
            ],
            options={
                "db_table": "generated_questions",
                "ordering": ["is_processed", "-last_score", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="conceptanswercache",
            index=models.Index(fields=["concept"], name="concept_cache_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="conceptanswercache",
            index=models.Index(fields=["quality_score", "confidence_score"], name="concept_cache_quality_idx"),
        ),
        migrations.AddConstraint(
            model_name="conceptrelationship",
            constraint=models.UniqueConstraint(fields=("concept", "related_concept", "relation_type"), name="unique_concept_relationship"),
        ),
        migrations.AddIndex(
            model_name="conceptrelationship",
            index=models.Index(fields=["concept", "weight"], name="concept_rel_concept_idx"),
        ),
        migrations.AddIndex(
            model_name="conceptrelationship",
            index=models.Index(fields=["related_concept", "weight"], name="concept_rel_related_idx"),
        ),
        migrations.AddConstraint(
            model_name="generatedquestion",
            constraint=models.UniqueConstraint(fields=("question", "source_chunk"), name="unique_generated_question_per_chunk"),
        ),
        migrations.AddIndex(
            model_name="generatedquestion",
            index=models.Index(fields=["subject_code", "concept"], name="genq_subject_concept_idx"),
        ),
        migrations.AddIndex(
            model_name="generatedquestion",
            index=models.Index(fields=["is_processed", "updated_at"], name="genq_process_state_idx"),
        ),
    ]
