# Generated by Django 5.2.6 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0017_generatedquestion_conceptanswercache_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetrievalStrategyCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("concept", models.CharField(max_length=150, unique=True)),
                ("best_context_chunk_count", models.PositiveSmallIntegerField(default=5)),
                ("best_keyword_weight", models.FloatField(default=0.7)),
                ("best_semantic_weight", models.FloatField(default=0.3)),
                ("best_rerank_strategy", models.CharField(default="semantic", max_length=50)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "retrieval_strategy_cache",
                "ordering": ["-confidence_score", "concept"],
            },
        ),
        migrations.AddIndex(
            model_name="retrievalstrategycache",
            index=models.Index(fields=["concept"], name="retr_strategy_concept_idx"),
        ),
        migrations.AddIndex(
            model_name="retrievalstrategycache",
            index=models.Index(fields=["confidence_score"], name="retr_strategy_conf_idx"),
        ),
    ]
