# Generated by Django 6.0.2 on 2026-03-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_retrievalstrategycache'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pdfimage',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='pdfimage',
            name='chatbot_pdf_referen_66fbf1_idx',
        ),
        migrations.RemoveIndex(
            model_name='pdfimage',
            name='chatbot_pdf_page_nu_ddfad1_idx',
        ),
        migrations.DeleteModel(
            name='PDFImage',
        ),
    ]
