# Generated by Django 6.0.2 on 2026-03-19 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_alter_pdfimage_unique_together_and_more'),
        ('courses', '0012_alter_subject_subject_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencepdf',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_pdfs', to='courses.lesson'),
        ),
    ]
