# Generated by Django 6.0.2 on 2026-03-19 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_unit_lesson_unit'),
        ('chatbot', '0020_referencepdf_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencepdf',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_pdfs', to='courses.unit'),
        ),
    ]
