from django.urls import path
from .views import (
    curriculum_chat,
    curriculum_chat_stream,
    curriculum_chat_history,
    delete_chat,
    system_architecture,
    upload_pdf,
    pdf_list,
    serve_reference_pdf,
    approve_pdf,
    hold_pdf,
    reject_pdf,
    toggle_pdf_reference,
    deactivate_pdf,
    reprocess_pdf,
    edit_pdf,
    delete_pdf,
    preview_pdf_chunks,
    pdf_text_api,
)

urlpatterns = [
    path('chat/', curriculum_chat, name="curriculum_chat"),
    path('chat/stream/', curriculum_chat_stream, name="curriculum_chat_stream"),
    path('chat/history/', curriculum_chat_history, name="curriculum_chat_history"),
    path('chat/<int:chat_id>/', delete_chat, name="delete_chat"),
    path('system-architecture/', system_architecture, name="system_architecture"),
    path('upload-pdf/', upload_pdf, name="upload_pdf"),
    path('pdfs/', pdf_list, name="pdf_list"),
    path('pdf-file/<int:pdf_id>/', serve_reference_pdf, name="serve_reference_pdf"),
    path('approve-pdf/<int:pdf_id>/', approve_pdf, name="approve_pdf"),
    path('hold-pdf/<int:pdf_id>/', hold_pdf, name="hold_pdf"),
    path('reject-pdf/<int:pdf_id>/', reject_pdf, name="reject_pdf"),
    path('toggle-pdf-reference/<int:pdf_id>/', toggle_pdf_reference, name="toggle_pdf_reference"),
    path('deactivate-pdf/<int:pdf_id>/', deactivate_pdf, name="deactivate_pdf"),
    path('reprocess-pdf/<int:pdf_id>/', reprocess_pdf, name="reprocess_pdf"),
    path('edit-pdf/<int:pdf_id>/', edit_pdf, name="edit_pdf"),
    path('delete-pdf/<int:pdf_id>/', delete_pdf, name="delete_pdf"),
    path('pdf-preview/<int:pdf_id>/', preview_pdf_chunks, name="preview_pdf_chunks"),
    path('api/pdf/<int:pdf_id>/', pdf_text_api, name="pdf_text_api"),
]
