# Generated by Django 6.0.2 on 2026-03-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_academic_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
