# Generated by Django 6.0.2 on 2026-03-13 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lesson_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['subject', 'order']},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['number', 'regulation']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['semester__number', 'name']},
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='history',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='courses.semester'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['user', 'viewed_at'], name='courses_his_user_id_df8c25_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['subject', 'order'], name='courses_les_subject_f03e26_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['semester', 'is_active'], name='courses_sub_semeste_8612e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='unique_bookmark_per_user_lesson'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('subject', 'order'), name='unique_lesson_order_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('number', 'regulation'), name='unique_semester_identity'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('semester', 'name'), name='unique_subject_per_semester'),
        ),
    ]
