# Generated by Django 6.0.2 on 2026-03-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_history_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('semester__isnull', False)), name='subject_requires_semester'),
        ),
    ]
