# Generated by Django 6.0.2 on 2026-03-19 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_subject_subject_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.subject')),
            ],
            options={
                'ordering': ['subject', 'unit_number'],
                'unique_together': {('subject', 'unit_number')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.unit'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['subject', 'unit_number'], name='courses_unit_subject_1ce13f_idx'),
        ),
    ]
