# Generated by Django 6.0.2 on 2026-03-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_unit_lesson_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
