# Generated by Django 6.0.2 on 2026-03-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_subject_branch'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='unit',
            new_name='courses_uni_subject_88520c_idx',
            old_name='courses_unit_subject_1ce13f_idx',
        ),
    ]
