# Generated by Django 6.0.2 on 2026-03-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Learner',
        ),
    ]
