# Generated by Django 6.0.2 on 2026-03-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_learner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('FACULTY', 'Faculty'), ('STUDENT', 'Student')], db_index=True, default='STUDENT', max_length=20),
        ),
    ]
